<style>
/* override default size and make it smaller */
div.innerwindows {
    width: 20% !important;
}
div.window div.has-innerwindows div.innercontent {
    width: 80% !important;
}
</style>
<script>
var classesList = {};

// on ready render properties
$(document).ready(function(){
    var rel = $("#relationsList");
    for(var i in relationsData){
        rel.append(
            '<a href="#" class="relationFilter" data-uri="'+i+'">'+relationsData[i]+'</a><br/>'
        );
    }

    var legend = $("#classesLegend");
    for(i in classesList){
        legend.append(
            '<span style="color:'+classesList[i]+';">'+i+'</span><br/>'
        );
    }
});
</script>
<div><a href="#" id="treeToggle">tree</a> | <a href="#" id="graphToggle">graph</a></div>
<br/>
<div id="relationsList">
<a href="#" class="relationFilter" data-uri="clear_all_filters">clear all filters</a><br/>
</div>
<br/>
<div id="classesLegend">
Colors:<br/>
</div>
